### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by KungZell** [HowieMa/TransFusion-Pose#2]
Thank you so much for sharing your project.  I am a beginner in this area, can you help me with deployment and 3D visualization?  Thank you very much.   @HowieMa

**Comment by HowieMa** [comment]
Hi, thanks for asking. 
Given the pre-trained model, you can run the following two scripts to obtain the predicted 3D coordinates. 

```
# Evaluation (2D)
python run/pose2d/valid.py --cfg experiments-local/h36m/transpose/256_fusion_enc3_GPE.yaml --gpus 0,1,2,3  

# Evaluation (3D)
python run/pose3d/estimate_tri.py --cfg experiments-local/h36m/transpose/256_fusion_enc3_GPE.yaml
```

Once you obtain the **'output_3d_joint.json'** file, you can use many tools to visualize the 3D keypoint. 
In my paper, I use Matplotlib to implement it and follow the code from [https://github.com/mks0601/3DMPPE_POSENET_RELEASE/issues/15](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/issues/15).

Here is an example code for Human 3.6M: 

```
def vis_3d_skeleton(kpt_3d, kpt_3d_vis, kps_lines, filename=None):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    cmap = plt.get_cmap('gnuplot')
    colors = [cmap(i) for i in np.linspace(0, 1, len(kps_lines) + 2)]
    colors = [np.array((c[2], c[1], c[0])) for c in colors]

    X, Y, Z = kpt_3d[:, 0], kpt_3d[:, 1], kpt_3d[:, 2]
    
    for i in range(len(kpt_3d)):
        x, y, z = X[i], Y[i], Z[i]
        ax.scatter(x, y, z, color=colors[i], marker='o')
#         ax.text(x, y, z, str(i))
    
    for l in range(len(kps_lines)):
        i1, i2 = kps_lines[l]
        x = np.array([X[i1], X[i2]])
        y = np.array([Y[i1], Y[i2]])
        z = np.array([Z[i1], Z[i2]])
        if kpt_3d_vis[i1,0] > 0 and kpt_3d_vis[i2,0] > 0:
            ax.plot(x, y, z, color=colors[l], linewidth=2)

    # boounding box
    max_range = np.array([X.max()-X.min(), Y.max()-Y.min(), Z.max()-Z.min()]).max()
    Xb = 0.5*max_range*np.mgrid[-1:2:2,-1:2:2,-1:2:2][0].flatten() + 0.5*(X.max()+X.min())
    Yb = 0.5*max_range*np.mgrid[-1:2:2,-1:2:2,-1:2:2][1].flatten() + 0.5*(Y.max()+Y.min())
    Zb = 0.5*max_range*np.mgrid[-1:2:2,-1:2:2,-1:2:2][2].flatten() + 0.5*(Z.max()+Z.min())
    for xb, yb, zb in zip(Xb, Yb, Zb):
        ax.plot([xb], [yb], [zb], 'w')

    ax.xaxis.set_ticklabels([])
    ax.yaxis.set_ticklabels([])
    ax.zaxis.set_ticklabels([])


skeleton = [
    [0, 1], 
    [0, 4], 
    [0, 7], 
    [1, 2], 
    [2, 3],
    [4, 5],
    [5, 6],
    [7, 8], 
    [8, 9], 
    [8, 11],
    [8, 14], 
    [9, 10], 
    [11, 12],
    [12, 13], 
    [14, 15],
    [15, 16]
]

kp_vis = np.ones((17, 1))
import json

key = 's_11_act_12_subact_01_000607'

all_results = json.load(open('output_3d_joint.json'))

kpt3d_pred = np.asarray(all_results[key]['GT'])
vis_3d_skeleton(kpt3d_pred, kp_vis, skeleton)
plt.savefig("GT_3D.pdf", bbox_inches='tight')
```
Hope my code is helpful to you!

**Comment by KungZell** [comment]
Thank you very much for your generous help, and with your help I have received the corresponding results.
I have another question, I would like to ask if I use two cameras as input, then can this project display the 3D inspection results in real time? How much real-time performance can be achieved if you can? Appreciate!!!

**Comment by HowieMa** [comment]
If you have only 2 views, you can obtain the 3D results, as triangulation requires at least 2 views. 

You can combine "valid.py" and "estimate_tri.py" together to implement the real-time visualization by yourself. 

As reported in my paper, the inference time of 2D pose (given images in different views, obtain the 2D pose via our framework) is around 0.032s on 2080Ti (Tab 1). Thus, I think it is enough to perform real-time visualization.  

The inference time of triangulation (2D-> 3D) and visualization with Matplotlib (the above code) can be varied on different devices, as they are CPU-only operations.

**Comment by KungZell** [comment]
Exciting news, thanks for your prompt reply.
