### ISSUE TITLE
Pre training model

### ISSUE THREAD

**Issue by jianlai123-123** [HowieMa/TransFusion-Pose#6]
Hello, because of the large amount of data, it is not easy to train; Can you provide the pre training model? Look forward to your reply, thank you!
@HowieMa

**Comment by HowieMa** [comment]
Hi, you can find the pre-trained model on Human 3.6M at the bottom of the README.md. 
<img width="996" alt="image" src="https://user-images.githubusercontent.com/25797674/203214036-782a6d3f-8056-4a2b-93cf-efb118242ebb.png">

If you refer to the pre-trained model on COCO, we directly use the model released by TransPose. You can also find it in the README.md file.  
<img width="957" alt="image" src="https://user-images.githubusercontent.com/25797674/203214351-fb496b8e-aea6-4f1b-8489-80611f77b3d6.png">

**Comment by jianlai123-123** [comment]
Thank you for your reply
