### ISSUE TITLE
pkl in pre training model

### ISSUE THREAD

**Issue by jianlai123-123** [HowieMa/TransFusion-Pose#7]
First of all, thank you for your contribution and sharing. I'm very interested in your project. I'd like to ask about the PKL files in the pre training. What is the function of the PKL file? Can I use it directly? Look forward to your reply, thank you again!
@HowieMa

**Comment by HowieMa** [comment]
May I ask which pkl file you refer to? 
If you are talking about the pkl file in the annotation, you can obtain it from the preprocessing of Human 3.6M.


![image](https://user-images.githubusercontent.com/25797674/207677989-c73e3b27-7d20-406c-aef2-4dda052f5fd0.png)

**Comment by jianlai123-123** [comment]
Hello, thank you for your reply. What I want to consult is the pkl file obtained from the download path. That is the document generated by the operation of other projects, and has nothing to do with this project, right? What I want to ask is the one marked in green.
<img width="437" alt="333" src="https://user-images.githubusercontent.com/117512033/207756193-5b276ffb-86a1-4e58-8641-9c8d2c634bb3.png">
<img width="322" alt="334" src="https://user-images.githubusercontent.com/117512033/207756215-257764f9-d9fa-4a26-9319-af61138f3ea3.png">
@HowieMa

**Comment by HowieMa** [comment]
Hi, I am sorry that I don't know how you get this `data.pkl` file. If you directly download the files from the provided Google Drive link, you should not have it. Here are all files inside the output folder. 
![image](https://user-images.githubusercontent.com/25797674/207835044-c13d9340-4d26-4202-95c6-7c976955aa07.png)


The file "**model_best_pth.tar**" is the weights for the trained model, which is obtained with` torch.save(...)` (see  [this code](https://github.com/HowieMa/TransFusion-Pose/blob/85556cb9c3b5ea169355395926a9ebde37f72c5d/lib/utils/utils.py#L94) for more detail)
You don't need to unzip it.

**Comment by jianlai123-123** [comment]
Thank you for your reply.
