### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by jianlai123-123** [HowieMa/TransFusion-Pose#8]
Hello, thank you for sharing. Your work is very meaningful to me. I want to ask a question. How often do I get a reply about the dataset Skipose when I apply to the owner. As shown, the following is what I want to apply for. Thanks again and look forward to your reply!
<img width="396" alt="212" src="https://user-images.githubusercontent.com/117512033/208292918-c8813607-e015-4574-915b-53a74bfee219.png">

**Comment by HowieMa** [comment]
Hi, sorry for the late reply. In 2021, I get a reply from the Ski-Pose team within a week. However, I don't know the current waiting time. There are other multi-view single-human datasets you may find helpful: 
ZJU-Mocap: https://chingswy.github.io/Dataset-Demo/ 
HuMMan: https://caizhongang.github.io/projects/HuMMan/

**Comment by jianlai123-123** [comment]
Thank you for your reply.
